/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graph;
import javax.swing.JOptionPane;
/**
 * Clase de la interfaz principal del programa (ver disponibilidad, realizar un pedido, y sección de administración que te redirecciona a otras ventanas especialmente para estas acciones).
 * @author Liliana Nóbrega
 */
public class mainWindow extends javax.swing.JFrame {

    public static Graph g;
    
    /** Creates new form mainWindow */
    public mainWindow(Graph g) {
        initComponents();
        this.g = g;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        bExit.setToolTipText("Haz click aquí para guardar y cerrar.");
        bAddWarehouse.setToolTipText("Haz click aquí para agregar un nuevo almacén al grafo.");
        bDeleteWarehouse.setToolTipText("Haz click aquí para eliminar un almacén del grafo.");
        bAdminStock.setToolTipText("Haz click aquí para gestionar el stock de uno de los almacenes.");
        bSeeGraph.setToolTipText("Haz click aquí para ver el grafo.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bAddWarehouse = new javax.swing.JButton();
        bSeeGraph = new javax.swing.JButton();
        bDeleteWarehouse = new javax.swing.JButton();
        bAdminStock = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("CLIENTES", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 360, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ADMINISTRACIÓN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, -1));

        jLabel2.setText("Haz click en el botón cuya acción quieres realizar:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 320, -1));

        bAddWarehouse.setText("AGREGAR UN ALMACÉN");
        bAddWarehouse.setToolTipText("Haz click aquí para agregar un nuevo almacén al grafo.");
        bAddWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddWarehouseActionPerformed(evt);
            }
        });
        jPanel2.add(bAddWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

        bSeeGraph.setText("VER GRAFO");
        bSeeGraph.setToolTipText("Haz click aquí para ver el grafo.");
        jPanel2.add(bSeeGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, 30));

        bDeleteWarehouse.setText("ELIMINAR UN ALMACÉN");
        bDeleteWarehouse.setToolTipText("Haz click aquí para eliminar un almacén del grafo.");
        bDeleteWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteWarehouseActionPerformed(evt);
            }
        });
        jPanel2.add(bDeleteWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        bAdminStock.setText("GESTIÓN DE STOCK");
        bAdminStock.setToolTipText("Haz click aquí para gestionar el stock de uno de los almacenes.");
        bAdminStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminStockActionPerformed(evt);
            }
        });
        jPanel2.add(bAdminStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 30));

        jLabel3.setText("almacenes y stock");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        jTabbedPane1.addTab("ADMINISTRACIÓN", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 320));

        bExit.setBackground(new java.awt.Color(255, 102, 153));
        bExit.setForeground(new java.awt.Color(255, 255, 255));
        bExit.setText("X");
        bExit.setToolTipText("Haz click aquí para guardar y cerrar.");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        //FALTA GUARDAR LOS DATOS DEL GRAFO EN EL TXT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        JOptionPane.showMessageDialog(null, "Hasta pronto, gracias por elegir Amazon.");
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bAddWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddWarehouseActionPerformed
        this.setVisible(false);
        addWarehouseWindow aww = new addWarehouseWindow(g, this);
    }//GEN-LAST:event_bAddWarehouseActionPerformed

    private void bDeleteWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteWarehouseActionPerformed
        this.setVisible(false);
        deleteWarehouseWindow dww = new deleteWarehouseWindow(g, this);
    }//GEN-LAST:event_bDeleteWarehouseActionPerformed

    private void bAdminStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminStockActionPerformed
        this.setVisible(false);
        stockAdministrationWindow saw = new stockAdministrationWindow(g, this);
    }//GEN-LAST:event_bAdminStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow(g).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddWarehouse;
    private javax.swing.JButton bAdminStock;
    private javax.swing.JButton bDeleteWarehouse;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSeeGraph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
