/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graph;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 * Clase de la interfaz principal del programa (ver disponibilidad, realizar un pedido, y sección de administración que te redirecciona a otras ventanas especialmente para estas acciones).
 * @author Liliana Nóbrega
 */
public class mainWindow extends javax.swing.JFrame {

    public static Graph g;
    public Warehouse warehouseToBuy;
    
    /** Creates new form mainWindow */
    public mainWindow(Graph g) {
        initComponents();
        this.g = g;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        bExit.setToolTipText("Haz click aquí para guardar y cerrar.");
        
        bAddWarehouse.setToolTipText("Haz click aquí para agregar un nuevo almacén al grafo.");
        bDeleteWarehouse.setToolTipText("Haz click aquí para eliminar un almacén del grafo.");
        bAdminStock.setToolTipText("Haz click aquí para gestionar el stock de uno de los almacenes.");
        
        bAvailableProduct.setToolTipText("Recuerda escribir en la casilla correspondiente el nombre del producto cuya disponibilidad deseas ver.");
        bAvailableProdsTotal.setToolTipText("Haz click aquí para ver la disponibilidad de productos de todos los almacenes.");
        bChooseWarehouse.setToolTipText("Haz click aquí para escoger de qué almacén realizarás la orden y luego iniciar el pedido.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bAvailableProduct = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        warehouseNameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        bAvailableProdsTotal = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bChooseWarehouse = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        availableNameTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bAddWarehouse = new javax.swing.JButton();
        bDeleteWarehouse = new javax.swing.JButton();
        bAdminStock = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 410, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("REALIZAR PEDIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel5.setText("ver disponibilidad y escoger productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, -1));

        bAvailableProduct.setText("VER DISPONIBILIDAD");
        bAvailableProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAvailableProductActionPerformed(evt);
            }
        });
        jPanel1.add(bAvailableProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel6.setText("VER DISPONIBILIDAD POR ALMACENES: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, 20));

        jLabel7.setText("cuya disponibilidad desea ver.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        warehouseNameTxt.setText("Introduce el nombre del almacén");
        warehouseNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(warehouseNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 220, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 410, 10));

        jLabel8.setText("VER DISPONIBILIDAD POR PRODUCTO: introduzca el nombre del producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        bAvailableProdsTotal.setText("VER DISPONIBILIDAD");
        bAvailableProdsTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAvailableProdsTotalActionPerformed(evt);
            }
        });
        jPanel1.add(bAvailableProdsTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 410, 10));

        jLabel9.setText("ESCOGER EL ALMACÉN DE DONDE ORDENAR: introduzca el nombre del");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel10.setText("almacén de donde ordenará.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        bChooseWarehouse.setText("ESCOGER ALMACÉN E INICIAR PEDIDO");
        bChooseWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseWarehouseActionPerformed(evt);
            }
        });
        jPanel1.add(bChooseWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 270, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 410, 10));

        availableNameTxt.setText("Introduce el nombre del producto");
        jPanel1.add(availableNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 220, -1));

        jTabbedPane1.addTab("CLIENTES", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 400, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ADMINISTRACIÓN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, -1));

        jLabel2.setText("Haga click en el botón cuya acción quiere realizar:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 320, -1));

        bAddWarehouse.setText("AGREGAR UN ALMACÉN");
        bAddWarehouse.setToolTipText("Haz click aquí para agregar un nuevo almacén al grafo.");
        bAddWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddWarehouseActionPerformed(evt);
            }
        });
        jPanel2.add(bAddWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 30));

        bDeleteWarehouse.setText("ELIMINAR UN ALMACÉN");
        bDeleteWarehouse.setToolTipText("Haz click aquí para eliminar un almacén del grafo.");
        bDeleteWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteWarehouseActionPerformed(evt);
            }
        });
        jPanel2.add(bDeleteWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        bAdminStock.setText("GESTIÓN DE STOCK");
        bAdminStock.setToolTipText("Haz click aquí para gestionar el stock de uno de los almacenes.");
        bAdminStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminStockActionPerformed(evt);
            }
        });
        jPanel2.add(bAdminStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, 30));

        jLabel3.setText("almacenes y stock");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 130, -1));

        jTabbedPane1.addTab("ADMINISTRACIÓN", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 360));

        bExit.setBackground(new java.awt.Color(255, 102, 153));
        bExit.setForeground(new java.awt.Color(255, 255, 255));
        bExit.setText("X");
        bExit.setToolTipText("Haz click aquí para guardar y cerrar.");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        txtFile.WriteTxt(g);
        JOptionPane.showMessageDialog(null, "Hasta pronto, gracias por elegir Amazon.");
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bAddWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddWarehouseActionPerformed
        this.setVisible(false);
        addWarehouseWindow aww = new addWarehouseWindow(g, this);
    }//GEN-LAST:event_bAddWarehouseActionPerformed

    private void bDeleteWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteWarehouseActionPerformed
        this.setVisible(false);
        deleteWarehouseWindow dww = new deleteWarehouseWindow(g, this);
    }//GEN-LAST:event_bDeleteWarehouseActionPerformed

    private void bAdminStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminStockActionPerformed
        this.setVisible(false);
        stockAdministrationWindow saw = new stockAdministrationWindow(g, this);
    }//GEN-LAST:event_bAdminStockActionPerformed

    private void bAvailableProdsTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAvailableProdsTotalActionPerformed
            String toPrint = "";
            toPrint += g.bfs();
            toPrint += "\n\n";
            toPrint += g.dfs();
            JTextArea text = new JTextArea(toPrint);
            text.setLineWrap(false);
            JScrollPane scrollPane = new JScrollPane(text);
            scrollPane.setPreferredSize(new Dimension(350, 300));
            JOptionPane.showMessageDialog(null, scrollPane, "Recorridos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bAvailableProdsTotalActionPerformed

    private void bAvailableProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAvailableProductActionPerformed
        if(availableNameTxt.getText().isBlank() || availableNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del producto antes de continuar.");
        }else{
            String toPrint = "";
            toPrint += g.bfsProduct(availableNameTxt.getText());
            toPrint += "\n\n";
            toPrint += g.dfsProduct(availableNameTxt.getText());
            JTextArea text = new JTextArea(toPrint);
            text.setLineWrap(false);
            JScrollPane scrollPane = new JScrollPane(text);
            scrollPane.setPreferredSize(new Dimension(350, 300));
            JOptionPane.showMessageDialog(null, scrollPane, "Recorridos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bAvailableProductActionPerformed

    private void bChooseWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseWarehouseActionPerformed
        if(warehouseNameTxt.getText().isBlank() || warehouseNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del almacén antes de continuar.");
        }else{
            warehouseToBuy = g.warehouses.getWarehouse(warehouseNameTxt.getText());
            if(warehouseToBuy != null){
                orderWindow ow = new orderWindow(g, warehouseToBuy, this);
                this.setVisible(false);
                warehouseNameTxt.setText("Introduce el nombre del almacén");
            }else{
                JOptionPane.showMessageDialog(null, "El nombre introducido no corresponde a ningún almacén.");
            }
        }
    }//GEN-LAST:event_bChooseWarehouseActionPerformed

    private void warehouseNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow(g).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availableNameTxt;
    private javax.swing.JButton bAddWarehouse;
    private javax.swing.JButton bAdminStock;
    private javax.swing.JButton bAvailableProdsTotal;
    private javax.swing.JButton bAvailableProduct;
    private javax.swing.JButton bChooseWarehouse;
    private javax.swing.JButton bDeleteWarehouse;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField warehouseNameTxt;
    // End of variables declaration//GEN-END:variables

}
