/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graph;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 * Clase asociada a la interfaz de la ventana donde se realiza un pedido
 * @author Liliana Nóbrega
 */
public class orderWindow extends javax.swing.JFrame {
    public static Graph g;
    public static Warehouse w;
    public static mainWindow prevWindow;
    boolean shortPath; 
    ProductList order;
    
    /** Creates new form orderWindow */
    public orderWindow(Graph g, Warehouse w, mainWindow prevWindow) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        this.g = g;
        this.w = w;
        this.prevWindow = prevWindow;
        this.order = new ProductList();
        
        bGoBack.setToolTipText("Haz click aquí para volver a la ventana principal (la orden no se guardará).");
        
        bDijkstra.setEnabled(true);
        bDijkstra.setToolTipText("Haz click aquí para escoger el algoritmo de Dijkstra como el algoritmo de búsqueda del almacén más cercano que complete la orden.");
        bFloydWarshall.setEnabled(true);
        bFloydWarshall.setToolTipText("Haz click aquí para escoger el algoritmo de Floyd-Warshall como el algoritmo de búsqueda del almacén más cercano que complete la orden.");
        
        productNameTxt.setEnabled(false);
        productNameTxt.setToolTipText("Escoge el algoritmo de búsqueda del camino más corto primero.");
        
        sProductAmmount.setEnabled(false);
        sProductAmmount.setToolTipText("Escoge el algoritmo de búsqueda del camino más corto primero.");
        
        bAddOrder.setEnabled(false);
        bAddOrder.setToolTipText("Escoge el algoritmo de búsqueda del camino más corto primero.");
        
        bFinishOrder.setEnabled(false);
        bFinishOrder.setToolTipText("Escoge el algoritmo de búsqueda del camino más corto primero.");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productNameTxt = new javax.swing.JTextField();
        sProductAmmount = new javax.swing.JSpinner();
        bAddOrder = new javax.swing.JButton();
        bFinishOrder = new javax.swing.JButton();
        bFloydWarshall = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bDijkstra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        bGoBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("REALIZAR PEDIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, -1));

        jLabel11.setText("REALIZAR PEDIDO: primero, escoja por cuál método se");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel12.setText("Luego, introduzca el producto y la cantidad.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 360, 20));

        productNameTxt.setText("Primero escoge el tipo de recorrido");
        jPanel1.add(productNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        sProductAmmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(sProductAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 70, 20));

        bAddOrder.setText("AÑADIR AL CARRITO");
        bAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddOrderActionPerformed(evt);
            }
        });
        jPanel1.add(bAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, 30));

        bFinishOrder.setText("TERMINAR ORDEN");
        bFinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinishOrderActionPerformed(evt);
            }
        });
        jPanel1.add(bFinishOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, -1));

        bFloydWarshall.setText("FLOYD-WARSHALL");
        bFloydWarshall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFloydWarshallActionPerformed(evt);
            }
        });
        jPanel1.add(bFloydWarshall, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 30));

        jLabel2.setText("buscará otro almacén cercano en caso de necesitarse para ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("completar su orden. ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        bDijkstra.setText("DIJKSTRA");
        bDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDijkstraActionPerformed(evt);
            }
        });
        jPanel1.add(bDijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 10));

        jLabel13.setText("Después de agregar al carrito, puede ingresar otro producto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 370, 20));

        bGoBack.setText("< Volver");
        bGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGoBackActionPerformed(evt);
            }
        });
        jPanel1.add(bGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel4.setText("o terminar.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoBackActionPerformed
        prevWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bGoBackActionPerformed

    private void bDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDijkstraActionPerformed
        this.shortPath = true;
        bFloydWarshall.setEnabled(false);
        bDijkstra.setEnabled(false);
        bFloydWarshall.setToolTipText("El método de búsqueda del almacén de menor distancia ya fue escogido: Dijkstra");
        bDijkstra.setToolTipText("El método de búsqueda del almacén de menor distancia ya fue escogido: Dijkstra");
        
        productNameTxt.setEnabled(true);
        productNameTxt.setText("Escribe aquí el nombre del producto a ordenar."); 
        sProductAmmount.setEnabled(true);
        sProductAmmount.setToolTipText("Escoge aquí la cantidad del producto ingresado que deseas comprar.");
        bAddOrder.setEnabled(true);
        bAddOrder.setToolTipText("Haz click aquí para añadir un nuevo producto con su cantidad a tu orden.");
        bFinishOrder.setToolTipText("Añade al menos un producto a tu pedido para terminar la orden.");
        
        
        
    }//GEN-LAST:event_bDijkstraActionPerformed

    private void bFloydWarshallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFloydWarshallActionPerformed
        this.shortPath = false;
        bFloydWarshall.setEnabled(false);
        bDijkstra.setEnabled(false);
        bFloydWarshall.setToolTipText("El método de búsqueda del almacén de menor distancia ya fue escogido: Floyd-Warshall.");
        bDijkstra.setToolTipText("El método de búsqueda del almacén de menor distancia ya fue escogido: Floyd-Warshall.");
        
        productNameTxt.setEnabled(true);
        productNameTxt.setText("Escribe aquí el nombre del producto a ordenar."); 
        sProductAmmount.setEnabled(true);
        sProductAmmount.setToolTipText("Escoge aquí la cantidad del producto ingresado que deseas comprar.");
        bAddOrder.setEnabled(true);
        bAddOrder.setToolTipText("Haz click aquí para añadir un nuevo producto con su cantidad a tu orden.");
        bFinishOrder.setToolTipText("Añade al menos un producto a tu pedido para terminar la orden.");
        
    }//GEN-LAST:event_bFloydWarshallActionPerformed

    private void bAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddOrderActionPerformed
        if(productNameTxt.getText().isBlank() || productNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del producto antes de continuar.");
        }else{
            if(this.order.isProductInList(productNameTxt.getText())){
                JOptionPane.showMessageDialog(null, "El producto ya está en la orden. Valide sus datos.");
            }else{
                this.order.addLast(productNameTxt.getText(), (Integer)sProductAmmount.getValue());
                if (!bFinishOrder.isEnabled()){
                    bFinishOrder.setEnabled(true);
                    bFinishOrder.setToolTipText("Haz click aquí para terminar tu orden.");
                }
                JOptionPane.showMessageDialog(null, "Producto añadido exitosamente al carrito de compra.");
            }
        }    
        
    }//GEN-LAST:event_bAddOrderActionPerformed

    private void bFinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinishOrderActionPerformed
        JTextArea text = new JTextArea(g.buy(w, order, shortPath));
        text.setLineWrap(false);
        JScrollPane scrollPane = new JScrollPane(text);  
        scrollPane.setPreferredSize(new Dimension(300, 300));
        JOptionPane.showMessageDialog(null, scrollPane, "Información de pedido.", JOptionPane.INFORMATION_MESSAGE);
        
        prevWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bFinishOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderWindow(g, w, prevWindow).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddOrder;
    private javax.swing.JButton bDijkstra;
    private javax.swing.JButton bFinishOrder;
    private javax.swing.JButton bFloydWarshall;
    private javax.swing.JButton bGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField productNameTxt;
    private javax.swing.JSpinner sProductAmmount;
    // End of variables declaration//GEN-END:variables

}
