/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graph;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 * Clase de la ventana de gestión de stock.
 * @author Liliana Nóbrega
 */
public class stockAdministrationWindow extends javax.swing.JFrame {

    public Warehouse w;
    public static Graph g;
    public static mainWindow prevWindow;
    
    /** Creates new form stockAdministrationWindow */
    public stockAdministrationWindow(Graph g, mainWindow prevWindow) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.g = g;
        this.prevWindow = prevWindow;
        bSubmitName.setEnabled(true);
        nameTxt.setEnabled(true);
        bExistingProducts.setEnabled(false);
        newProductTxt.setEnabled(false);
        sNewProductAmmount.setEnabled(false);
        bAddNewProduct.setEnabled(false);
        existingProductTxt.setEnabled(false);
        sExistingProductAmmount.setEnabled(false);
        bIncreaseProduct.setEnabled(false);
        bExistingWarehouses.setToolTipText("Haz click aquí para ver los nombres de los almacenes ya existentes.");
        nameTxt.setToolTipText("Tip: para asegurarte de que estás introduciendo el nombre de un almacén existente, puedes ver los almacenes preexistentes.");
        bExistingProducts.setToolTipText("Debes ingresar el nombre del almacén escogido para desbloquear estas opciones.");
        newProductTxt.setText("Debes ingresar el nombre del almacén.");
        existingProductTxt.setText("Debes ingresar el nombre del almacén.");
        sNewProductAmmount.setToolTipText("Debes ingresar el nombre del almacén escogido para desbloquear estas opciones.");
        sExistingProductAmmount.setToolTipText("Debes ingresar el nombre del almacén escogido para desbloquear estas opciones.");
        bAddNewProduct.setToolTipText("Debes ingresar el nombre del almacén escogido para desbloquear estas opciones.");
        bIncreaseProduct.setToolTipText("Debes ingresar el nombre del almacén escogido para desbloquear estas opciones.");
    }
    
    public stockAdministrationWindow(Graph g, mainWindow prevWindow, Warehouse newW){ //se llama a este constructor cuando se crea un nuevo almacén (el cual se pasa como parámetro), con el fin de llenar el stock de este nuevo almacén.
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.g = g;
        this.prevWindow = prevWindow;
        this.w = newW;
        bBack.setEnabled(false);
        bSubmitName.setEnabled(false);
        nameTxt.setEnabled(false);
        bExistingProducts.setEnabled(true);
        newProductTxt.setEnabled(true);
        sNewProductAmmount.setEnabled(true);
        bAddNewProduct.setEnabled(true);
        existingProductTxt.setEnabled(true);
        sExistingProductAmmount.setEnabled(true);
        bIncreaseProduct.setEnabled(true);
        bSubmitName.setToolTipText("El almacén ya fue escogido.");
        nameTxt.setText("El almacén ya fue escogido.");
        bExistingProducts.setToolTipText("Haz click aquí para ver los productos que tiene el almacén "+w.getName()+" en su stock.");
        newProductTxt.setText("Ingrese el nombre del producto");
        existingProductTxt.setText("Ingrese el nombre del producto");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bExistingWarehouses = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newProductTxt = new javax.swing.JTextField();
        sNewProductAmmount = new javax.swing.JSpinner();
        bAddNewProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        existingProductTxt = new javax.swing.JTextField();
        sExistingProductAmmount = new javax.swing.JSpinner();
        bIncreaseProduct = new javax.swing.JButton();
        bSubmitName = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        bExistingProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("GESTIÓN DE STOCK DE UN ALMACÉN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, -1));

        bExistingWarehouses.setText("Ver almacenes preexistentes");
        bExistingWarehouses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExistingWarehousesActionPerformed(evt);
            }
        });
        jPanel1.add(bExistingWarehouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, -1));

        jLabel2.setText("manejar: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("Primero, ingrese el nombre del almacén cuyo stock desea");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        nameTxt.setText("Ingrese el nombre del almacén");
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 10));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Ingrese el nombre del nuevo producto que desea añadir y");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel7.setText("y la cantidad que añadirá:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        newProductTxt.setText("Ingrese el nombre del producto");
        jPanel2.add(newProductTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, -1));

        sNewProductAmmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel2.add(sNewProductAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, -1));

        bAddNewProduct.setText("Añadir nuevo producto");
        bAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddNewProductActionPerformed(evt);
            }
        });
        jPanel2.add(bAddNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 190, -1));

        jTabbedPane1.addTab("Producto NUEVO", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("y la cantidad que añadirá:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setText("Ingrese el nombre del producto del cual aumentará el stock");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        existingProductTxt.setText("Ingrese el nombre del producto");
        jPanel3.add(existingProductTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, -1));

        sExistingProductAmmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel3.add(sExistingProductAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, -1));

        bIncreaseProduct.setText("Aumentar cantidad de producto");
        bIncreaseProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIncreaseProductActionPerformed(evt);
            }
        });
        jPanel3.add(bIncreaseProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, -1));

        jTabbedPane1.addTab("Producto EXISTENTE", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 360, 150));

        bSubmitName.setText("Escoger almacén");
        bSubmitName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitNameActionPerformed(evt);
            }
        });
        jPanel1.add(bSubmitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        bBack.setText("< Volver");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        jPanel1.add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        bExistingProducts.setText("Ver productos de almacén");
        bExistingProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExistingProductsActionPerformed(evt);
            }
        });
        jPanel1.add(bExistingProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExistingWarehousesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExistingWarehousesActionPerformed
        JTextArea text = new JTextArea(g.warehouses.getWarehouseNames());
        text.setLineWrap(false);
        JScrollPane scrollPane = new JScrollPane(text);
        scrollPane.setPreferredSize(new Dimension(200, 100));
        JOptionPane.showMessageDialog(null, scrollPane, "Almacenes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bExistingWarehousesActionPerformed

    private void bSubmitNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitNameActionPerformed
        if(nameTxt.getText().isBlank() || nameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre antes de continuar.");
        }else{
            w = g.warehouses.getWarehouse(nameTxt.getText());
            if(w != null){
                bExistingProducts.setEnabled(true);
                newProductTxt.setEnabled(true);
                sNewProductAmmount.setEnabled(true);
                bAddNewProduct.setEnabled(true);
                existingProductTxt.setEnabled(true);
                sExistingProductAmmount.setEnabled(true);
                bIncreaseProduct.setEnabled(true);
                bSubmitName.setEnabled(false);
                bSubmitName.setToolTipText("El almacén ya fue escogido.");
                nameTxt.setEnabled(false);
                nameTxt.setText("El almacén ya fue escogido.");
                bExistingProducts.setToolTipText("Haz click aquí para ver los productos que tiene el almacén "+w.getName()+" en su stock.");
                newProductTxt.setText("Ingrese el nombre del producto");
                existingProductTxt.setText("Ingrese el nombre del producto");
                sNewProductAmmount.setToolTipText(null);
                sExistingProductAmmount.setToolTipText(null);
                bAddNewProduct.setToolTipText(null);
                bIncreaseProduct.setToolTipText(null);
            }else{
                JOptionPane.showMessageDialog(null, "El nombre introducido no corresponde a ningún almacén.");
            }
        }
    }//GEN-LAST:event_bSubmitNameActionPerformed

    private void bExistingProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExistingProductsActionPerformed
        JTextArea text = new JTextArea(w.showStock());
        text.setLineWrap(true);
        JScrollPane scrollPane = new JScrollPane(text);
        scrollPane.setPreferredSize(new Dimension(200, 100));
        JOptionPane.showMessageDialog(null, scrollPane, "Productos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bExistingProductsActionPerformed

    private void bIncreaseProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIncreaseProductActionPerformed
        if(existingProductTxt.getText().isBlank() || existingProductTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del producto antes de continuar.");
        }else{
            w.getStock().increaseProductStock(existingProductTxt.getText(), (Integer)sExistingProductAmmount.getValue());
        }
    }//GEN-LAST:event_bIncreaseProductActionPerformed

    private void bAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddNewProductActionPerformed
        if(newProductTxt.getText().isBlank() || newProductTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del producto antes de continuar.");
        }else{
            if (!w.getStock().isProductInList(newProductTxt.getText())){
                w.getStock().addNewProductToStock(newProductTxt.getText(), (Integer)sNewProductAmmount.getValue());
                if (!bBack.isEnabled() && !w.getStock().isEmpty()){
                    bBack.setEnabled(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "El producto ingresado no es nuevo: ya se encuentra en el stock. Para aumentar productos existentes, haga click en la otra pestaña.");
            }
        }
    }//GEN-LAST:event_bAddNewProductActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        prevWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bBackActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockAdministrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockAdministrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockAdministrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockAdministrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockAdministrationWindow(g, prevWindow).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddNewProduct;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bExistingProducts;
    private javax.swing.JButton bExistingWarehouses;
    private javax.swing.JButton bIncreaseProduct;
    private javax.swing.JButton bSubmitName;
    private javax.swing.JTextField existingProductTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField newProductTxt;
    private javax.swing.JSpinner sExistingProductAmmount;
    private javax.swing.JSpinner sNewProductAmmount;
    // End of variables declaration//GEN-END:variables

}
